# Config file for RandomItem by LDX;

# Interval in minutes to give a random item;
Interval: 10

# List of random items for the plugin to choose from; Format: ID:Damage:Amount
# -金矿石
# -铁矿石
# -煤炭
# -木头
# -床
# -TNT
# -钻石
# -火把
# -黑曜石
# -铁锹
# -铁搞
# -铁斧
# -铁剑
# -打火机
# -钻石剑
# -钻石搞
# -金剑
# -金斧
# -指南针
# -弓
# -箭
# -蛋糕
# -金苹果
# -附魔台
# -牛仔裤
# -钟表
# -牛奶
# -岩浆桶
Items:
- "14:0:1"
- "15:0:2"
- "16:0:4"
- "17:0:9"
- "355:0:1"
- "46:0:4"
- "264:0:1"
- "50:0:24"
- "49:0:16"
- "256:0:1"
- "257:0:1"
- "258:0:1"
- "267:0:1"
- "259:0:1"
- "276:0:1"
- "278:0:1"
- "283:0:1"
- "286:0:1"
- "345:0:1"
- "261:0:1"
- "262:0:64"
- "354:0:1"
- "322:0:2"
- "116:0:1"
- "300:0:1"
- "347:0:1"
- "335:0:1"
- "327:0:1"

# Should players recieve an item when they kill another player?
Kill: false

GiftCode:
- "123456:35:0:1"
- "2048:35:0:1"